cargo-features = ["edition2024"]
[package]
name = "bytecodeinterpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
ordered-float = "5.0.0"
phf = { version = "0.11.3", features = ["macros"] }
regex = "1.11.1"
regex-split = "0.1.0"
